# Generated by Django 5.0.8 on 2024-08-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0003_rename_session_title_session_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_occupany",
            field=models.IntegerField(default=0),
        ),
    ]
