# Generated by Django 5.0.8 on 2024-08-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0004_session_session_occupany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_code",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
