# Generated by Django 5.0.8 on 2024-10-22 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0005_alter_session_session_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
