# Generated by Django 5.0.8 on 2024-10-22 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_username_gin_idx_user_netid_gin_idx_and_more"),
        ("session", "0006_alter_session_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="session.session",
            ),
        ),
    ]
