# Generated by Django 5.0.8 on 2024-08-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessioninvitation",
            name="session",
        ),
    ]
