# Generated by Django 5.0.8 on 2024-08-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0002_remove_sessioninvitation_session"),
        ("session", "0005_alter_session_session_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessioninvitation",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="session.session",
            ),
        ),
    ]
